### Assignment 2 - Numpy and Pandas Basics

As you have already gone through the first assignment which was based on **Python** basics, you should have realised that these assignments are a lot easier than your normal **Mookit** assignments. Take your time and write down your solutions to each of the questions mentioned below. 😃

In [2]:
## importing the Necessary libraries
import numpy as np
import pandas as pd

- Firstly, create a numpy array consisting of all 1's having a size of 7:8

In [5]:
a = np.ones(56).reshape(7,8)
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

- Create a random numpy array consisting of 10 elements ranging from 1 to 100.

In [8]:
d1 = np.random.random_integers(1, 100+1, 10)
d1


/tmp/ipykernel_9864/2710995154.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 101 + 1) instead
  d1 = np.random.random_integers(1, 100+1, 10)


array([19, 50, 66, 81, 17, 48, 49, 15, 73, 14])

- This was quite easy right :p, now you are given with two numpy arrays, namely [1,2] and [3,4], write the code to create all possible combinations of these two numpy arrays.

In [9]:
a=np.array([1,2])
b=np.array([3,4])
print(np.array(np.meshgrid(a,b)).T.reshape(-1,2))

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


- Create a square matrix of your choice and calculate the maximum, minimum element and their corresponding indexes using numpy.

In [10]:
x=np.array([[3,5],[1,2]])
mi=x.min()
ma=x.max()
a=np.nonzero(x==mi)
b=np.nonzero(x==ma)
print(mi,a,ma,b)

1 (array([1]), array([0])) 5 (array([0]), array([1]))


- from the above matrix that you have created, calculate the determinant and the eigenvalues using numpy.

In [12]:
d=np.linalg.det(x)
print((round(d)))
e=np.linalg.eig(x)
print(e)

1
(array([4.79128785, 0.20871215]), array([[ 0.94140906, -0.87315384],
       [ 0.33726692,  0.48744474]]))


- Given a polynomial $x^{3} + 4x^{2} + 5x + 6 = 0$, calculate the roots of the equation using numpy.

In [13]:
co=np.array([1,4,5,6])
print(np.roots(co))

[-3. +0.j         -0.5+1.32287566j -0.5-1.32287566j]


- Create two 2-D numpy arrays, the first array should contain all the elements ranging from 0 to 10, having 2 rows and the second 2-D arrays should containing 10 numbers between 1 and 20, having a size of 2x5. 
- After creating the two 2-D numpy arrays, stack them vertically to create a 4x5 matrix.
- Convert the 4x5 matrix to a 1x1 numpy array
- Finally count the frequency of each of the elements occuring in the array.

In [16]:
arr1=np.arange(10).reshape(2,5)
arr2=np.random.randint(1,20,10).reshape(2,5)
print("arr2=",arr2)
arr3=np.vstack((arr1,arr2))
print("stacked array=",arr3)
arr4=arr3.ravel()
print(arr4)
c=np.unique(arr4,return_counts="True")
print(c)

arr2= [[ 5 18 11 18  5]
 [12 19 18  1 14]]
stacked array= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 5 18 11 18  5]
 [12 19 18  1 14]]
[ 0  1  2  3  4  5  6  7  8  9  5 18 11 18  5 12 19 18  1 14]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 14, 18, 19]), array([1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 1]))


- Convert the following dictionary to a Pandas Dataframe

In [18]:
data ={'area': ['new-hills', 'cape-town', 'mumbai','new Delhi', 'Kanpur'],
       'rainfall':[100, 70, 200, 30, 25],
       'temperature':[20, 25, 39, 45, 47]}
a=pd.DataFrame(data)
print(a)

        area  rainfall  temperature
0  new-hills       100           20
1  cape-town        70           25
2     mumbai       200           39
3  new Delhi        30           45
4     Kanpur        25           47


- Using the dataframe created above:
   - Display all the info related to the dataframe.
   - replace the entry **"new-hills"** with **"old-hills"** and replace the raingfall amount **100** with **99**.
   - sort the entries, rainfall amount should be **ascending order** and the temperature should be **descending order**.

- Using the **csv file** present, use pandas to read the **csv** file in a dataframe.
- Firstly, use **pandas info()** method to display the datatypes of the entries present in each column in the dataframe.
- Find the number of **null entries (NaN)** values in each column and show it as an output.
- Replace the `~1000` in the **Depth (in meters)** and `~3300` in **Depth (in feet)** columns with `1000` and `3300` and display the modified dataframe.
- Also calculate the rows corresponding to the maximum values

In [70]:
# Write your code here