### Assignment 2 - Numpy and Pandas Basics

As you have already gone through the first assignment which was based on **Python** basics, you should have realised that these assignments are a lot easier than your normal **Mookit** assignments. Take your time and write down your solutions to each of the questions mentioned below. 😃

In [60]:
## importing the Necessary libraries
import numpy as np
import pandas as pd

- Firstly, create a numpy array consisting of all 1's having a size of 7:8

In [69]:

a = np.ones((7,8))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


- Create a random numpy array consisting of 10 elements ranging from 1 to 100.

In [3]:
import numpy as np
b = np.random.randint(1,101,size = 10)
print(b)

[80 26 88 80 41 57 91 63 99 74]


- This was quite easy right :p, now you are given with two numpy arrays, namely [1,2] and [3,4], write the code to create all possible combinations of these two numpy arrays.

In [6]:

a =np.array([1,2])
b= np.array([3,4])
c = np.random.randn(2)
d = a*c[0] + b*c[1]
print(d)


[ -9.84686058 -13.36880609]


- Create a square matrix of your choice and calculate the maximum, minimum element and their corresponding indexes using numpy.

In [13]:

a = np.array([[1,2,3],[11,10,113],[-11,114,0]])
print("Maximum is ", a.max()," at ",np.unravel_index(np.argmax(a),a.shape))
print("Minimum is ",a.min()," at ",np.unravel_index(np.argmin(a),a.shape))

Maximum is  114  at  (2, 1)
Minimum is  -11  at  (2, 0)


- from the above matrix that you have created, calculate the determinant and the eigenvalues using numpy.

In [62]:

a = np.array([[1,2,3],[11,10,113],[-11,114,0]])
x = np.linalg.det(a)
print("Determinant of a is", x)
y = np.linalg.eigvals(a)
print("Eigenvalues of a are : ",y)

Determinant of a is -11276.000000000002
Eigenvalues of a are :  [   0.87615492 -108.4964022   118.62024727]


- Given a polynomial $x^{3} + 4x^{2} + 5x + 6 = 0$, calculate the roots of the equation using numpy.

In [7]:
coefficient = np.array([1,4,5,6])
y = np.roots(coefficient)
print("ROOTS are : ",y)

ROOTS are :  [-3. +0.j         -0.5+1.32287566j -0.5-1.32287566j]


- Create two 2-D numpy arrays, the first array should contain all the elements ranging from 0 to 10, having 2 rows and the second 2-D arrays should containing 10 numbers between 1 and 20, having a size of 2x5. 
- After creating the two 2-D numpy arrays, stack them vertically to create a 4x5 matrix.
- Convert the 4x5 matrix to a 1x1 numpy array
- Finally count the frequency of each of the elements occuring in the array.

In [33]:
a = np.arange(10).reshape(2,5)

b = np.linspace(2,20,num=10).reshape(2,5)

a = a.transpose()

b = b.transpose()

c =np.concatenate((a,b),axis =1)
print(c)
c = c.flatten()
y = len(c)
z = np.unique(c, return_counts = True)
(a,counts) =np.unique(c,return_counts=True)
print (np.asarray((a , counts)))


[[ 0.  5.  2. 12.]
 [ 1.  6.  4. 14.]
 [ 2.  7.  6. 16.]
 [ 3.  8.  8. 18.]
 [ 4.  9. 10. 20.]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 12. 14. 16. 18. 20.]
 [ 1.  1.  2.  1.  2.  1.  2.  1.  2.  1.  1.  1.  1.  1.  1.  1.]]


- Convert the following dictionary to a Pandas Dataframe

In [35]:
import pandas as pd
data ={'area': ['new-hills', 'cape-town', 'mumbai','new Delhi', 'Kanpur'],
       'rainfall':[100, 70, 200, 30, 25],
       'temperature':[20, 25, 39, 45, 47]}
## Write your code here

Frame = pd.DataFrame.from_dict(data)


area  rainfall  temperature
0  new-hills       100           20
1  cape-town        70           25
2     mumbai       200           39
3  new Delhi        30           45
4     Kanpur        25           47

- Using the dataframe created above:
   - Display all the info related to the dataframe.
   - replace the entry **"new-hills"** with **"old-hills"** and replace the raingfall amount **100** with **99**.
   - sort the entries, rainfall amount should be **ascending order** and the temperature should be **descending order**.

In [37]:

Frame.loc[0,('area')] = 'old-hills'


Frame.loc[0,('rainfall')] =99
print(Frame)

Rainfall = Frame.sort_values(by = ['rainfall'])
print("Ranifall : ") 
print(Rainfall)
Temperature = Frame.sort_values(by = ['temperature'])
print("Temperature :")
print(Temperature)

        area  rainfall  temperature
0  old-hills        99           20
1  cape-town        70           25
2     mumbai       200           39
3  new Delhi        30           45
4     Kanpur        25           47
Ranifall : 
        area  rainfall  temperature
4     Kanpur        25           47
3  new Delhi        30           45
1  cape-town        70           25
0  old-hills        99           20
2     mumbai       200           39
Temperature :
        area  rainfall  temperature
0  old-hills        99           20
1  cape-town        70           25
2     mumbai       200           39
3  new Delhi        30           45
4     Kanpur        25           47


- Using the **csv file** present, use pandas to read the **csv** file in a dataframe.
- Firstly, use **pandas info()** method to display the datatypes of the entries present in each column in the dataframe.
- Find the number of **null entries (NaN)** values in each column and show it as an output.
- Replace the `~1000` in the **Depth (in meters)** and `~3300` in **Depth (in feet)** columns with `1000` and `3300` and display the modified dataframe.
- Also calculate the rows corresponding to the maximum values

In [102]:
# Write your code here
Data = pd.read_csv('lakes.csv')

print (Data.isna().sum())
Data['Depth (in meters)'] = Data['Depth (in meters)'].replace(['~1000'],'1000')
Data['Depth (in feet)'] = Data['Depth (in feet)'].replace(['~3300'],'3300')
depth = Data['Depth (in meters)']
x = np.unravel_index(np.argmax(Data['Depth (in feet)']) , Data['Depth (in feet)'].shape)

print(Data.iloc[x])
Data

Name                 0
Country              0
Reigon               8
Depth (in meters)    0
Depth (in feet)      0
Depth^2/area         0
dtype: int64
Name                    Baikal
Country                 Russia
Reigon                 Siberia
Depth (in meters)         1642
Depth (in feet)           5387
Depth^2/area         9.22×10−6
Name: 0, dtype: object


Name  \
0                         Baikal   
1                     Tanganyika   
2                    Caspian sea   
3                         Vostok   
4           O'Higgins-San Martín   
5            Malawi/Nyasa/Niassa   
6                      Issyk Kul   
7                    Great Slave   
8                         Crater   
9                         Matano   
10  General Carrera-Buenos Aires   
11              Hornindalsvatnet   
12                       Quesnel   
13                          Toba   
14                         Sarez   
15                         Tahoe   
16                     Argentino   
17                          Kivu   
18                    Salsvatnet   
19                  Nahuel Huapi   
20                       Hauroko   
21      Cochrane / Pueyrredón[6]   
22                     Lake Tinn   
23                         Adams   
24                        Chelan   
25                        Van[7]   
26                          Poso   
27                       Fagnano   
28                    Great Bear   
29                     Manapouri   
30                         Mjøsa   
31                          Como   
32                       Te Anau   
33                        Tazawa   
34                      Wakatipu   
35                      Superior   

                                              Country  \
0                                              Russia   
1    Tanzania, Democratic Republic of the Congo, B...   
2    Iran, Russia, Turkmenistan, Kazakhstan, Azerb...   
3                                          Antarctica   
4                                    Chile, Argentina   
5                        Mozambique, Malawi, Tanzania   
6                                          Kyrgyzstan   
7                                              Canada   
8                                       United States   
9                                           Indonesia   
10                                  Chile,  Argentina   
11                                             Norway   
12                                             Canada   
13                                          Indonesia   
14                                         Tajikistan   
15                                      United States   
16                                          Argentina   
17          Democratic Republic of the Congo,  Rwanda   
18                                             Norway   
19                                          Argentina   
20                                        New Zealand   
21                                  Chile,  Argentina   
22                                             Norway   
23                                             Canada   
24                                      United States   
25                                             Turkey   
26                                          Indonesia   
27                                  Argentina,  Chile   
28                                             Canada   
29                                        New Zealand   
30                                             Norway   
31                                              Italy   
32                                        New Zealand   
33                                              Japan   
34                                        New Zealand   
35                                             Canada   

                                     Reigon Depth (in meters) Depth (in feet)  \
0                                   Siberia              1642            5387   
1                               East Africa              1470            4823   
2                                       NaN              1025            3363   
3                                       NaN              1000            3300   
4     Aysén (Chile), Santa Cruz (Argentina)               836            2742   
5                                       NaN               706            2316   
6                 