### Assignment 2 - Numpy and Pandas Basics

As you have already gone through the first assignment which was based on **Python** basics, you should have realised that these assignments are a lot easier than your normal **Mookit** assignments. Take your time and write down your solutions to each of the questions mentioned below. 😃

In [11]:
## importing the Necessary libraries
import numpy as np
import pandas as pd

- Firstly, create a numpy array consisting of all 1's having a size of 7:8

In [3]:
## Write your code here
a = np.ones((7,8))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


- Create a random numpy array consisting of 10 elements ranging from 1 to 100.

In [25]:
# Write your code here
x = np.random.randint(100, size=(10))
print(x)

[53 53 24 39 67 49 91 79 20 77]


- This was quite easy right :p, now you are given with two numpy arrays, namely [1,2] and [3,4], write the code to create all possible combinations of these two numpy arrays.

In [30]:
## Write your code here
x = [1,2]
y = [3,4]
z = np.array(np.meshgrid(x, y)).T.reshape(-1,3)
print(z)

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


- Create a square matrix of your choice and calculate the maximum, minimum element and their corresponding indexes using numpy.

In [34]:
## Write your code here
s = np.array([[1,4],[5,8]])
x=s.min()
print(np.where(s==x))
y=s.max()
print(np.where(s==y))
print(x,y)


(array([0], dtype=int64), array([0], dtype=int64))
(array([1], dtype=int64), array([1], dtype=int64))
1 8


- from the above matrix that you have created, calculate the determinant and the eigenvalues using numpy.

In [43]:
## Write your code here
a = np.array([[1,4],[5,8]])
det = np.linalg.det(a)
print(round(det))

l = np.linalg.eig(a)
print(l)


-12
(array([-1.17890835, 10.17890835]), array([[-0.87816399, -0.39949624],
       [ 0.47835971, -0.91673483]]))


- Given a polynomial $x^{3} + 4x^{2} + 5x + 6 = 0$, calculate the roots of the equation using numpy.

In [42]:
## Write your code here
zigzig = ([1, 4, 5, 6])
chigchig = np.roots(zigzig)
print(chigchig)


[-3. +0.j         -0.5+1.32287566j -0.5-1.32287566j]


- Create two 2-D numpy arrays, the first array should contain all the elements ranging from 0 to 10, having 2 rows and the second 2-D arrays should containing 10 numbers between 1 and 20, having a size of 2x5. 
- After creating the two 2-D numpy arrays, stack them vertically to create a 4x5 matrix.
- Convert the 4x5 matrix to a 1x1 numpy array
- Finally count the frequency of each of the elements occuring in the array.

In [9]:
## Write your code here
import numpy as np
a1=np.arange(10).reshape(2,5)
a2=np.random.randint(1,20,10).reshape(2,5)
print("a2=",a2)
a3=np.vstack((a1,a2))
print("stacked array=",a3)
a4=a3.ravel()
print(a4)
res=np.unique(a4,return_counts="True")
print(res)


a2= [[ 7 15 10 19 19]
 [ 6  2  7 12  3]]
stacked array= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 7 15 10 19 19]
 [ 6  2  7 12  3]]
[ 0  1  2  3  4  5  6  7  8  9  7 15 10 19 19  6  2  7 12  3]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 15, 19]), array([1, 1, 2, 2, 1, 1, 2, 3, 1, 1, 1, 1, 1, 2], dtype=int64))


- Convert the following dictionary to a Pandas Dataframe

In [68]:
data ={'area': ['new-hills', 'cape-town', 'mumbai','new Delhi', 'Kanpur'],
       'rainfall':[100, 70, 200, 30, 25],
       'temperature':[20, 25, 39, 45, 47]}
## Write your code here

- Using the dataframe created above:
   - Display all the info related to the dataframe.
   - replace the entry **"new-hills"** with **"old-hills"** and replace the raingfall amount **100** with **99**.
   - sort the entries, rainfall amount should be **ascending order** and the temperature should be **descending order**.

In [57]:
## write your code here
data ={'area': ['new-hills', 'cape-town', 'mumbai','new Delhi', 'Kanpur'],
       'rainfall':[100, 70, 200, 30, 25],
       'temperature':[20, 25, 39, 45, 47]}
a=pd.DataFrame(data)
print(a.info())

newa = a.replace('new-hills', 'old-hills')
print(newa)

boom = a.replace(100, 90)
print(boom)

a.sort_values(by=['rainfall'], inplace=True)
print(a)

a.sort_values(by=['temperature'], inplace=True, ascending=False)
print(a)




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   area         5 non-null      object
 1   rainfall     5 non-null      int64 
 2   temperature  5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes
None
        area  rainfall  temperature
0  old-hills       100           20
1  cape-town        70           25
2     mumbai       200           39
3  new Delhi        30           45
4     Kanpur        25           47
        area  rainfall  temperature
0  new-hills        90           20
1  cape-town        70           25
2     mumbai       200           39
3  new Delhi        30           45
4     Kanpur        25           47
        area  rainfall  temperature
4     Kanpur        25           47
3  new Delhi        30           45
1  cape-town        70           25
0  new-hills       100           20
2     mumbai       200 

- Using the **csv file** present, use pandas to read the **csv** file in a dataframe.
- Firstly, use **pandas info()** method to display the datatypes of the entries present in each column in the dataframe.
- Find the number of **null entries (NaN)** values in each column and show it as an output.
- Replace the `~1000` in the **Depth (in meters)** and `~3300` in **Depth (in feet)** columns with `1000` and `3300` and display the modified dataframe.
- Also calculate the rows corresponding to the maximum values

In [13]:
# Write your code here
a=pd.read_csv("lakes.csv")
print(a.info())
print(pd.isna(a).sum())
a["Depth (in meters)"].replace(~1000,1000,inplace=True)
a["Depth (in feet)"].replace(~3300,3300,inplace=True)
print(a)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Name               36 non-null     object
 1   Country            36 non-null     object
 2   Reigon             28 non-null     object
 3   Depth (in meters)  36 non-null     object
 4   Depth (in feet)    36 non-null     object
 5   Depth^2/area       36 non-null     object
dtypes: object(6)
memory usage: 1.8+ KB
None
Name                 0
Country              0
Reigon               8
Depth (in meters)    0
Depth (in feet)      0
Depth^2/area         0
dtype: int64
                            Name  \
0                         Baikal   
1                     Tanganyika   
2                    Caspian sea   
3                         Vostok   
4           O'Higgins-San Martín   
5            Malawi/Nyasa/Niassa   
6                      Issyk Kul   
7                    Great Slave   
8 